Dockerfile for frontend
Drakon5999/GKAI pull request #4
Opened 2023-03-05 18:30 UTC by KarineAyrs

2023-03-06 17:36 UTC, KarineAyrs commented
тык

2023-03-06 17:37 UTC, Drakon5999 requested changes

2023-03-06 17:37 UTC, Drakon5999 commented on frontend/Dockerfile
> +COPY . .
А это точно нужно? =)

2023-03-06 17:37 UTC, Drakon5999 commented on frontend/Dockerfile
> +RUN npm install react-scripts
По поводу этого тоже не уверен, мне казалось, что достаточно выполнить `npm install`

2023-03-06 17:37 UTC, Drakon5999 commented on frontend/Dockerfile
> +WORKDIR /frontend
По хорошему надо запускать не так, потому что так ты запускаешь приложение в отладочном режиме, где оно будет дико тормозить.
Нужно создать production билд и запускать его
https://stackoverflow.com/questions/49208528/how-to-run-build-version-using-create-react-app

2023-03-06 18:17 UTC, KarineAyrs commented on frontend/Dockerfile
> +RUN npm install react-scripts
У меня без `react-scripts` не поднимается. Но возможно, я что-то делаю не так

2023-03-06 18:22 UTC, KarineAyrs commented on frontend/Dockerfile
> +WORKDIR /frontend
Поняла

2023-03-06 18:28 UTC, KarineAyrs commented on frontend/Dockerfile
> +COPY . .
Workdir тебе не нравится? Без него все копируется в корень. Могу назвать его по-другому, если название не подходит)

2023-03-07 04:31 UTC, Drakon5999 commented on frontend/Dockerfile
> +COPY . .
Нет, мне не нравится `COPY . .`

2023-03-10 10:55 UTC, KarineAyrs commented on frontend/Dockerfile
> +COPY . .
Я его использую потому что еще нигде не прописала mount (это сделаю в общем docker-compose файле). Иначе, файлы из текущей директории не будут доступны в контейнере

2023-03-16 18:51 UTC, Drakon5999 approved these changes

2023-03-16 18:52 UTC, merged