Small fixes and design improvements
Drakon5999/GKAI pull request #5
Opened 2023-03-08 09:49 UTC by Drakon5999

2023-03-17 11:56 UTC, KarineAyrs commented
Запустила. 

1. В этой версии почему-то не работает кнопка "Выберите файл"
2. Для чего новое окошко слева и должен ли быть там текст: 
``` 
[
  {
    "props": "val"
  },
  {
    "other": "val"
  }
]
```


"Выберите файл" из прошлой версии:

2023-03-17 12:00 UTC, KarineAyrs requested changes
Написала комментарий выше (ниже?)

2023-03-18 08:01 UTC, Drakon5999 commented
> Написала комментарий выше

Поправил: забыл удалить код, который использовал для тестирования

2023-03-31 09:19 UTC, KarineAyrs approved these changes

2023-03-31 09:21 UTC, merged