Docker fastapi
Drakon5999/GKAI pull request #7
Opened 2023-03-17 11:36 UTC by KarineAyrs

Запустила часть Леши (на мой взгляд всё нормально) и написала для нее Dockerfile.  
`python-multipart` не было в requirements, но при его отсутствии у меня возникали ошибки. Его, наверное, можно будет добавить в requirements в будущем.

2023-03-18 07:56 UTC, Drakon5999 requested changes

2023-03-18 07:56 UTC, Drakon5999 commented on fastapi/Dockerfile
> +ENTRYPOINT ["uvicorn", "main:app",  "--host", "0.0.0.0", "--port", "8800"]
Проверь, что в конце файлов есть переносы строк. Это важно для линукс систем

2023-03-18 07:56 UTC, Drakon5999 commented on fastapi/Dockerfile
> +RUN pip install python-multipart
Так давай сразу перенесём в requirements?

2023-03-21 09:26 UTC, KarineAyrs commented on fastapi/Dockerfile
> +RUN pip install python-multipart
Поправила

2023-03-21 17:25 UTC, Drakon5999 approved these changes

2023-03-21 18:48 UTC, merged